services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    command: ["serve", "-s", "dist", "-l", "3000", "--no-clipboard"]
